### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by imSanko** [imSanko/Image_Caption_Generator_With_Transformers#2]
Deployment isn't working!!

> If anyone can help me your must welcome with an PR

**Comment by chandan1995** [comment]
@imSanko renaming requirement.txt to requirements.txt worked for me
https://github.com/chandan1995/Image_Caption_Generator_With_Transformers

![image](https://github.com/imSanko/Image_Caption_Generator_With_Transformers/assets/11442556/30e82cdc-1c63-49b4-b0bb-02f6309b81c3)

**Comment by imSanko** [comment]
I'm trying to deploy the project which is giving me the ERROR:

ModuleNotFoundError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
```
File "/home/adminuser/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "/mount/src/image_caption_generator_with_transformers/app.py", line 2, in <module>
    from transformers import VisionEncoderDecoderModel, ViTFeatureExtractor, AutoTokenizer
```

**Comment by imSanko** [comment]
@chandan1995 Have you forked my REPO ??

**Comment by chandan1995** [comment]
Hello @imSanko  , have pushed a pull request, kindly check

**Comment by imSanko** [comment]
WORKING BUT Oh no.
Error running app. If you need help, try the [Streamlit docs](https://docs.streamlit.io/en/stable/deploy_streamlit_app.html) and [forums](https://discuss.streamlit.io/c/13).
`[07:17:38] 📦 Processed dependencies!
/home/adminuser/venv/lib/python3.11/site-packages/transformers/models/vit/feature_extraction_vit.py:28: FutureWarning: The class ViTFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ViTImageProcessor instead.
  warnings.warn(
/app/scripts/run-streamlit.sh: line 9:   197 Killed                  sudo -E -u appuser /home/adminuser/venv/bin/streamlit "$@"`
