### ISSUE TITLE
ADD: Dark mode in app.py

### ISSUE THREAD

**Issue by imSanko** [imSanko/Image_Caption_Generator_With_Transformers#3]
### We need to use dark mode or the switch case for the webpage.

1. Fork my Repository.
2. Run > `Requirement.py`.
3. Run > `Streamlit run app.py`

**Comment by imSanko** [comment]
Please ADD:
### Describe your change:

Fixes #11316. There is a bug in the code that doesn't handle the edge case when the insertion of an empty string is done.

* Fix a bug or typo in an existing algorithm?

### Checklist:

* This pull request is all my own work -- I have not plagiarized.
* I know that pull requests will not be merged if they fail the automated tests.
* This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
* All filenames are in all lowercase characters with no spaces or dashes.
* All function parameters and return values are annotated with Python type hints.
* All functions have doctests that pass the automated testing.
* If this pull request resolves one or more open issues then the description above includes the issue number(s) with a closing keyword: "Fixes #ISSUE-NUMBER".
* I have read CONTRIBUTING.md.
* All functions and variable names follow Python naming conventions.
* All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* All new Python files are placed inside an existing directory.
* Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* Documentation change?

**Comment by chandan1995** [comment]
@imSanko - this flag defaults to dark mode. 
streamlit run app.py base="dark"

**Comment by imSanko** [comment]
> @imSanko - this flag defaults to dark mode. streamlit run app.py base="dark"

Yes, It does but I was thinking of making some changes around the corner with having a SWITCH.

**Comment by imSanko** [comment]
FIXED WITH INBUILD DARK AND OTHER MODE
